# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setTabletTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        
        boxlayout =  QtWidgets.QVBoxLayout()
        self.scrollArea = QtWidgets.QScrollArea()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        # self.scrollArea.setSizePolicy(sizePolicy)
        scroll_widget = QtWidgets.QWidget()
        scroll_widget.setLayout(boxlayout)
        self.scrollArea.setWidget(scroll_widget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        # self.scrollArea.setHorizontalScrollBarPolicy(1)
        # self.scrollArea.setVerticalScrollBarPolicy(1)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 550, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        

        self.app_cards = {}
        for i in range(10):
            self.app_cards[i] = {}
            self.app_cards[i]['frame'] = QtWidgets.QFrame(self.scrollAreaWidgetContents)
            self.app_cards[i]['frame'].setGeometry(QtCore.QRect(10, 10+(110*i), 510, 100))
            self.app_cards[i]['frame'].setSizePolicy(sizePolicy)
            self.app_cards[i]['frame'].setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.app_cards[i]['frame'].setFrameShadow(QtWidgets.QFrame.Raised)
            self.app_cards[i]['frame'].setObjectName("frame")
            self.app_cards[i]['radioButton'] = QtWidgets.QRadioButton(self.app_cards[i]['frame'])
            self.app_cards[i]['radioButton'].setGeometry(QtCore.QRect(370, 40, 111, 23))
            self.app_cards[i]['radioButton'].setObjectName("radioButton")
            self.app_cards[i]['label'] = QtWidgets.QLabel(self.app_cards[i]['frame'])
            self.app_cards[i]['label'].setGeometry(QtCore.QRect(10, 20, 81, 71))
            self.app_cards[i]['label'].setObjectName("label")
            self.app_cards[i]['label_2'] = QtWidgets.QLabel(self.app_cards[i]['frame'])
            self.app_cards[i]['label_2'].setGeometry(QtCore.QRect(190, 40, 66, 21))
            self.app_cards[i]['label_2'].setObjectName("label_2")




        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.vboxlayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


        for i in range(10):
            self.app_cards[i]['radioButton'].setText(_translate("MainWindow", "RadioButton"))
            self.app_cards[i]['label'].setText(_translate("MainWindow", "TextLabel"))
            self.app_cards[i]['label_2'].setText(_translate("MainWindow", "TextLabel"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


# self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
# self.label_3.setText(_translate("MainWindow", "TextLabel"))
# self.label_4.setText(_translate("MainWindow", "TextLabel"))
# self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
# self.label_5.setText(_translate("MainWindow", "TextLabel"))
# self.label_6.setText(_translate("MainWindow", "TextLabel"))





# self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
# self.frame_2.setGeometry(QtCore.QRect(10, 120, 501, 101))
# self.frame_2.setSizePolicy(sizePolicy)
# self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
# self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
# self.frame_2.setObjectName("frame_2")
# self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
# self.radioButton_2.setGeometry(QtCore.QRect(370, 40, 111, 23))
# self.radioButton_2.setObjectName("radioButton_2")
# self.label_3 = QtWidgets.QLabel(self.frame_2)
# self.label_3.setGeometry(QtCore.QRect(10, 20, 81, 71))
# self.label_3.setObjectName("label_3")
# self.label_4 = QtWidgets.QLabel(self.frame_2)
# self.label_4.setGeometry(QtCore.QRect(190, 40, 66, 21))
# self.label_4.setObjectName("label_4")
# self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
# self.frame_3.setGeometry(QtCore.QRect(10, 230, 501, 101))
# sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
# sizePolicy.setHorizontalStretch(0)
# sizePolicy.setVerticalStretch(0)
# sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
# self.frame_3.setSizePolicy(sizePolicy)
# self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
# self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
# self.frame_3.setObjectName("frame_3")
# self.radioButton_3 = QtWidgets.QRadioButton(self.frame_3)
# self.radioButton_3.setGeometry(QtCore.QRect(370, 40, 111, 23))
# self.radioButton_3.setObjectName("radioButton_3")
# self.label_5 = QtWidgets.QLabel(self.frame_3)
# self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 71))
# self.label_5.setObjectName("label_5")
# self.label_6 = QtWidgets.QLabel(self.frame_3)
# self.label_6.setGeometry(QtCore.QRect(190, 40, 66, 21))
# self.label_6.setObjectName("label_6")